import { ComponentStory, ComponentMeta } from '@storybook/react-native';
import Text from '../Text/Text';
declare const TextMeta: ComponentMeta<typeof Text>;
export default TextMeta;
declare type TextStory = ComponentStory<typeof Text>;
export declare const Heading: TextStory;
export declare const SubtitleXLarge: TextStory;
export declare const SubtitleLarge: TextStory;
export declare const SubtitleMedium: TextStory;
export declare const SubtitleSmall: TextStory;
export declare const Body: TextStory;
export declare const Caption: TextStory;
