export declare const space: number[];
export declare const fontSizes: number[];
export declare const radii: {
    none: number;
    small: number;
    normal: number;
    large: number;
    xlarge: number;
};
export declare const colors: {
    white: string;
    black: string;
    transparent: string;
    primaryColor: string;
    secondaryColor: string;
    tertiaryColor: string;
    successColor: string;
    dangerColor: string;
    warningColor: string;
    alternativeColor: string;
    featuredColor: string;
    primaryHover: string;
    secondaryHover: string;
    tertiaryHover: string;
    successHover: string;
    dangerHover: string;
    warningHover: string;
    alternativeHover: string;
    featuredHover: string;
    primaryBackground: string;
    accentBackground: string;
    secondaryBackground: string;
    tertiaryBackground: string;
    successBackground: string;
    alertBackground: string;
    warningBackground: string;
    infoBackground: string;
    featuredCBackground: string;
    borderColor: string;
    contentPrimary: string;
    contentSecondary: string;
    contentTertiary: string;
    contentPassive: string;
    gradientPurple: string[];
    gradientOrange: string[];
};
declare const _default: {
    space: number[];
    fontSizes: number[];
    radii: {
        none: number;
        small: number;
        normal: number;
        large: number;
        xlarge: number;
    };
    colors: {
        white: string;
        black: string;
        transparent: string;
        primaryColor: string;
        secondaryColor: string;
        tertiaryColor: string;
        successColor: string;
        dangerColor: string;
        warningColor: string;
        alternativeColor: string;
        featuredColor: string;
        primaryHover: string;
        secondaryHover: string;
        tertiaryHover: string;
        successHover: string;
        dangerHover: string;
        warningHover: string;
        alternativeHover: string;
        featuredHover: string;
        primaryBackground: string;
        accentBackground: string;
        secondaryBackground: string;
        tertiaryBackground: string;
        successBackground: string;
        alertBackground: string;
        warningBackground: string;
        infoBackground: string;
        featuredCBackground: string;
        borderColor: string;
        contentPrimary: string;
        contentSecondary: string;
        contentTertiary: string;
        contentPassive: string;
        gradientPurple: string[];
        gradientOrange: string[];
    };
};
export default _default;
